name: chiza_ai
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0
  
  # ðŸ‘‡ STICK TO THIS EXACT VERSION
  llama_cpp_dart: ^0.1.2+1
  
  provider: ^6.1.1
  # If you get warnings about this, don't worry for now, or use ^0.6.14
  flutter_markdown: ^0.6.14
  path_provider: ^2.1.2
  dio: ^5.4.0
  permission_handler: ^11.0.0
  flutter_downloader: ^1.11.7
  file_picker: ^8.0.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_logo.png"
  min_sdk_android: 21 

flutter:
  uses-material-design: true
  assets:
    - assets/icon/